spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/virtualacademy 

spring.datasource.username=2EXrcSX8dsM71b3.root
spring.datasource.password=Y9r9O8q2yNT8oUcv

spring.jpa.generate-ddl=true
#create, create-drop
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql=true



