#database
spring.datasource.url=jdbc:mysql://localhost:3306/s_managementv2
spring.datasource.username=root
spring.datasource.password=root
#spring.jpa.database-platform = org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
#create, create-drop
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE