spring.application.name=smsv2
server.port=9091

spring.profiles.active=${ENV:dev}

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sagnikghosh904@gmail.com
spring.mail.password=lgpbkwdgtinijdzc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#sms phone
twilio.accountSid=AC48e19136e44977c81ee27185807cc202
twilio.authToken=c73e2e89aaf5b5ba5b90a2bdcbdcc08f
twilio.phoneNumber=+18149923843



#enable multipart
spring.servlet.multipart.enabled=true


#max file size
spring.servlet.multipart.max-file-size=20MB


#min file size
#spring.servlet.multipart.file-size-threshold=10MB